#pragma once


/* GENERAL */
#define ONESHOT_TAP_TOGGLE   0
#define TAPPING_TERM       200


/* MOUSE */
#define MK_3_SPEED
#define MK_MOMENTARY_ACCEL
#define MOUSEKEY_DELAY      100
#define MOUSEKEY_INTERVAL    10
#define MOUSEKEY_MAX_SPEED    8
#define MK_C_OFFSET_UNMOD    16
#define MK_C_INTERVAL_UNMOD  16
#define MK_C_OFFSET_0         1
#define MK_C_INTERVAL_0      16
#define MK_C_OFFSET_1         4
#define MK_C_INTERVAL_1      16
#define MK_C_OFFSET_2        32
#define MK_C_INTERVAL_2      16


/* OLED */
#ifdef OLED_DRIVER_ENABLE
#	define OLED_FONT_WIDTH  8
#	define OLED_FONT_HEIGHT 8
#	define OLED_FONT_START  0x00
#	define OLED_FONT_END    0x8F
#	define OLED_FONT_H      "users/njdoyle/njd_oled_font.c"
#endif


/* RGB */
#ifdef RGB_MATRIX_ENABLE

#	define RGB_DISABLE_WHEN_USB_SUSPENDED true
#	define RGB_DISABLE_TIMEOUT 120000
#	define RGB_MATRIX_HUE_STEP  8
#	define RGB_MATRIX_SAT_STEP 16
#	define RGB_MATRIX_VAL_STEP  8
#	define RGB_MATRIX_SPD_STEP 16

#	define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#	define RGB_MATRIX_KEYPRESSES

//#	define DISABLE_RGB_MATRIX_SOLID_COLOR
#	define DISABLE_RGB_MATRIX_ALPHAS_MODS
#	define DISABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#	define DISABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
//#	define DISABLE_RGB_MATRIX_BREATHING
#	define DISABLE_RGB_MATRIX_BAND_SAT
//#	define DISABLE_RGB_MATRIX_BAND_VAL
#	define DISABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#	define DISABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#	define DISABLE_RGB_MATRIX_BAND_SPIRAL_SAT
//#	define DISABLE_RGB_MATRIX_BAND_SPIRAL_VAL
//#	define DISABLE_RGB_MATRIX_CYCLE_ALL
#	define DISABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#	define DISABLE_RGB_MATRIX_CYCLE_UP_DOWN
#	define DISABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#	define DISABLE_RGB_MATRIX_CYCLE_OUT_IN
//#	define DISABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#	define DISABLE_RGB_MATRIX_CYCLE_PINWHEEL
#	define DISABLE_RGB_MATRIX_CYCLE_SPIRAL
#	define DISABLE_RGB_MATRIX_DUAL_BEACON
#	define DISABLE_RGB_MATRIX_RAINBOW_BEACON
#	define DISABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#	define DISABLE_RGB_MATRIX_RAINDROPS
#	define DISABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
//#	define DISABLE_RGB_MATRIX_TYPING_HEATMAP
#	define DISABLE_RGB_MATRIX_DIGITAL_RAIN
//#	define DISABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
//#	define DISABLE_RGB_MATRIX_SOLID_REACTIVE
#	define DISABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
//#	define DISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#	define DISABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
//#	define DISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#	define DISABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
//#	define DISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#	define DISABLE_RGB_MATRIX_SPLASH
#	define DISABLE_RGB_MATRIX_MULTISPLASH
#	define DISABLE_RGB_MATRIX_SOLID_SPLASH
//#	define DISABLE_RGB_MATRIX_SOLID_MULTISPLASH

#endif


/* AUDIO */
#ifdef AUDIO_ENABLE
#	define DEFAULT_LAYER_SONGS { \
		SONG(QWERTY_SOUND ), \
		SONG(DVORAK_SOUND ), \
		SONG(COLEMAK_SOUND), \
		SONG(COLEMAK_SOUND), \
		SONG(COLEMAK_SOUND), \
		SONG(WORKMAN_SOUND)  \
	}
#endif
