#pragma once

#define \
	NJD_BASE_LAYOUT( \
		NJD_KM_Q, NJD_KM_W, NJD_KM_E, NJD_KM_R, NJD_KM_T, NJD_KM_Y, NJD_KM_U, NJD_KM_I    , NJD_KM_O  , NJD_KM_P     , \
		NJD_KM_A, NJD_KM_S, NJD_KM_D, NJD_KM_F, NJD_KM_G, NJD_KM_H, NJD_KM_J, NJD_KM_K    , NJD_KM_L  , NJD_KM_SCOLON, \
		NJD_KM_Z, NJD_KM_X, NJD_KM_C, NJD_KM_V, NJD_KM_B, NJD_KM_N, NJD_KM_M, NJD_KM_COMMA, NJD_KM_DOT, NJD_KM_SLASH , \
		NJD_KM_LMAMOD, NJD_KM_BSPACE  , \
		NJD_KM_LMIMOD, NJD_KM_RMAMOD  , \
		NJD_KM_LSHIFT, NJD_KM_RSHIFT  , \
		NJD_KM_SPACE , NJD_KM_ENTER   , \
		NJD_KM_NUMBER, NJD_KM_SYMBOL  , \
		NJD_KM_LALT  , NJD_KM_FUNCTION  \
	) \
	LAYOUT( \
		NJD_KM_LMAMOD, NJD_KM_Q, NJD_KM_W, NJD_KM_E, NJD_KM_R, NJD_KM_T,      NJD_KM_Y, NJD_KM_U, NJD_KM_I    , NJD_KM_O  , NJD_KM_P     , NJD_KM_BSPACE, \
		NJD_KM_LMIMOD, NJD_KM_A, NJD_KM_S, NJD_KM_D, NJD_KM_F, NJD_KM_G,      NJD_KM_H, NJD_KM_J, NJD_KM_K    , NJD_KM_L  , NJD_KM_SCOLON, NJD_KM_RMAMOD, \
		NJD_KM_LSHIFT, NJD_KM_Z, NJD_KM_X, NJD_KM_C, NJD_KM_V, NJD_KM_B,      NJD_KM_N, NJD_KM_M, NJD_KM_COMMA, NJD_KM_DOT, NJD_KM_SLASH , NJD_KM_RSHIFT, \
		                       NJD_KM_LALT, NJD_KM_NUMBER, NJD_KM_SPACE,      NJD_KM_ENTER, NJD_KM_SYMBOL, NJD_KM_FUNCTION \
	)

